In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

In [ ]:
#loading data
df = pd.read_csv('/content/DATA (1).csv')
df

           Car       Model  Volume  Weight  CO2  Unnamed: 5
0       Toyota        Aygo    1000     790   99         NaN
1   Mitsubishi  Space Star    1200    1160   95         NaN
2        Skoda      Citigo    1000     929   95         NaN
3         Fiat         500     900     865   90         NaN
4         Mini      Cooper    1500    1140  105         NaN
5           VW         Up!    1000     929  105         NaN
6        Skoda       Fabia    1400    1109   90         NaN
7     Mercedes     A-Class    1500    1365   92         NaN
8         Ford      Fiesta    1500    1112   98         NaN
9         Audi          A1    1600    1150   99         NaN
10     Hyundai         I20    1100     980   99         NaN
11      Suzuki       Swift    1300     990  101         NaN
12        Ford      Fiesta    1000    1112   99         NaN
13       Honda       Civic    1600    1252   94         NaN
14      Hundai         I30    1600    1326   97         NaN
15        Opel       Astra    1600    1330   97         NaN
16         BMW           1    1600    1365   99         NaN
17       Mazda           3    2200    1280  104         NaN
18       Skoda       Rapid    1600    1119  104         NaN
19        Ford       Focus    2000    1328  105         NaN
20        Ford      Mondeo    1600    1584   94         NaN
21        Opel    Insignia    2000    1428   99         NaN
22    Mercedes     C-Class    2100    1365   99         NaN
23       Skoda     Octavia    1600    1415   99         NaN
24       Volvo         S60    2000    1415   99         NaN
25    Mercedes         CLA    1500    1465  102         NaN
26        Audi          A4    2000    1490  104         NaN
27        Audi          A6    2000    1725  114         NaN
28       Volvo         V70    1600    1523  109         NaN
29         BMW           5    2000    1705  114         NaN
30    Mercedes     E-Class    2100    1605  115         NaN
31       Volvo        XC70    2000    1746  117         NaN
32        Ford       B-Max    1600    1235  104         NaN
33         BMW           2    1600    1390  108         NaN
34        Opel      Zafira    1600    1405  109         NaN
35    Mercedes         SLK    2500    1395  120         NaN

In [ ]:
df.head(15)

           Car       Model  Volume  Weight  CO2  Unnamed: 5
0       Toyota        Aygo    1000     790   99         NaN
1   Mitsubishi  Space Star    1200    1160   95         NaN
2        Skoda      Citigo    1000     929   95         NaN
3         Fiat         500     900     865   90         NaN
4         Mini      Cooper    1500    1140  105         NaN
5           VW         Up!    1000     929  105         NaN
6        Skoda       Fabia    1400    1109   90         NaN
7     Mercedes     A-Class    1500    1365   92         NaN
8         Ford      Fiesta    1500    1112   98         NaN
9         Audi          A1    1600    1150   99         NaN
10     Hyundai         I20    1100     980   99         NaN
11      Suzuki       Swift    1300     990  101         NaN
12        Ford      Fiesta    1000    1112   99         NaN
13       Honda       Civic    1600    1252   94         NaN
14      Hundai         I30    1600    1326   97         NaN

In [ ]:
df.tail()

         Car   Model  Volume  Weight  CO2  Unnamed: 5
31     Volvo    XC70    2000    1746  117         NaN
32      Ford   B-Max    1600    1235  104         NaN
33       BMW       2    1600    1390  108         NaN
34      Opel  Zafira    1600    1405  109         NaN
35  Mercedes     SLK    2500    1395  120         NaN

In [ ]:
df.shape

(36, 6)

In [ ]:
df.columns
Index['car', 'model', 'volume', 'weight', 'CO2', 'unnamed: 5']

NameError: name 'Index' is not defined

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Car         36 non-null     object
 1   Model       36 non-null     object
 2   Volume      36 non-null     int64
 3   Weight      36 non-null     int64
 4   CO2         36 non-null     int64
 5   Unnamed: 5  0 non-null      float64
dtypes: float64(1), int64(3), object(2)
memory usage: 1.8+ KB

In [ ]:
df = df.drop('Unnamed: 5', axis = 1)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Car     36 non-null     object
 1   Model   36 non-null     object
 2   Volume  36 non-null     int64
 3   Weight  36 non-null     int64
 4   CO2     36 non-null     int64
dtypes: int64(3), object(2)
memory usage: 1.5+ KB

In [ ]:
df['Car'].value_counts()

Car
Ford          5
Mercedes      5
Skoda         4
Volvo         3
Audi          3
BMW           3
Opel          3
Toyota        1
Mini          1
VW            1
Mitsubishi    1
Fiat          1
Hyundai       1
Hundai        1
Honda         1
Suzuki        1
Mazda         1
Name: count, dtype: int64

In [ ]:
df['Model'].value_counts()

Model
Fiesta        2
Space Star    1
Aygo          1
Citigo        1
500           1
Up!           1
Cooper        1
Fabia         1
A-Class       1
A1            1
I20           1
Swift         1
Civic         1
I30           1
Astra         1
1             1
3             1
Rapid         1
Focus         1
Mondeo        1
Insignia      1
C-Class       1
Octavia       1
S60           1
CLA           1
A4            1
A6            1
V70           1
5             1
E-Class       1
XC70          1
B-Max         1
2             1
Zafira        1
SLK           1
Name: count, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Car'] = le.fit_transform(df['Car'])
df['Model'] = le.fit_transform(df['Model'])
df

    Car  Model  Volume  Weight  CO2
0    14     10    1000     790   99
1    10     29    1200    1160   95
2    12     14    1000     929   95
3     2      4     900     865   90
4     9     16    1500    1140  105
5    15     31    1000     929  105
6    12     18    1400    1109   90
7     8      5    1500    1365   92
8     3     19    1500    1112   98
9     0      6    1600    1150   99
10    6     21    1100     980   99
11   13     30    1300     990  101
12    3     19    1000    1112   99
13    4     15    1600    1252   94
14    5     22    1600    1326   97
15   11      9    1600    1330   97
16    1      0    1600    1365   99
17    7      2    2200    1280  104
18   12     26    1600    1119  104
19    3     20    2000    1328  105
20    3     24    1600    1584   94
21   11     23    2000    1428   99
22    8     12    2100    1365   99
23   12     25    1600    1415   99
24   16     27    2000    1415   99
25    8     13    1500    1465  102
26    0      7    2000    1490  104
27    0      8    2000    1725  114
28   16     32    1600    1523  109
29    1      3    2000    1705  114
30    8     17    2100    1605  115
31   16     33    2000    1746  117
32    3     11    1600    1235  104
33    1      1    1600    1390  108
34   11     34    1600    1405  109
35    8     28    2500    1395  120

In [ ]:
# clean columns
df.columns = df.columns.str.strip().str.lower()

# encode categorical
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['car'] = le.fit_transform(df['car'])
df['model'] = le.fit_transform(df['model'])

# features & target
x = df[['car', 'volume', 'model', 'weight']]
y = df['co2']

# split & train
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [ ]:
car_input = int(input("Enter the car name: "))
volume_input = float(input("Enter the volume: "))
model_input = int(input("Enter the model name: "))
weight_input = float(input("Enter the weight: "))

input_data = [[car_input, volume_input, model_input, weight_input]]

predicted_co2 = model.predict(input_data)

print(f"Predicted CO2 emission: {predicted_co2[0]}")

Enter the car name: 45
Enter the volume: 600
Enter the model name: 4
Enter the weight: 5678
Predicted CO2 emission: 124.0021516824051

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [ ]:
predicted_co2 = model.predict(input_data)
print(f"Predicted CO2 emission: {predicted_co2[0]}")

Predicted CO2 emission: 124.0021516824051

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(